# Generated by Django 2.1.5 on 2019-02-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalStore', '0002_auto_20190221_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiryDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturedDate',
            field=models.DateField(),
        ),
    ]
