# Generated by Django 2.1.5 on 2019-02-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0004_auto_20190212_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contactNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rollNumber',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
