# Generated by Django 2.1.5 on 2019-02-13 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0005_auto_20190213_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
