# Generated by Django 2.1.5 on 2019-02-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0010_prescription_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='ENT', max_length=100),
            preserve_default=False,
        ),
    ]
