# Generated by Django 2.1.5 on 2019-04-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0014_auto_20190227_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='password',
            new_name='passwordHash',
        ),
    ]
