# Generated by Django 2.1.5 on 2019-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0015_auto_20190401_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='password',
            new_name='passwordHash',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='emailHash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emailHash',
            field=models.CharField(max_length=64),
        ),
    ]
