# Generated by Django 2.1.5 on 2019-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalStore', '0003_auto_20190221_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
