# Generated by Django 2.1.5 on 2019-02-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalStore', '0004_medicine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='photoId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
