# Generated by Django 2.1.5 on 2019-02-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0002_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='000000', max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='rollNumber',
            field=models.CharField(default='000000', max_length=8),
        ),
    ]
