# Generated by Django 2.1.5 on 2019-02-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0009_auto_20190214_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
