# Generated by Django 2.1.5 on 2019-02-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0012_auto_20190220_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
