# Generated by Django 2.1.5 on 2019-02-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0013_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='emailHash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='emailHash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
